#Travis config
language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install requests
# to fix the dependencies with appengine
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.8.zip -nv
# old version: - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
- unzip -q google_appengine_1.9.8.zip
# command to run tests, e.g. python setup.py test
script:  
  #- nosetests tests/
  #- nosetests tests/test_parsers.py
  #- nosetests tests/test_parser_youtube.py
  #- nosetests tests/test_homehandlers.py
  #- nosetests tests/test_requests.py
  #- nosetests --with-color  tests/test_parsers.py # no color matey. but the fabric guy does it.
  # nosetests --with-gae
  bash -x run_tests.sh

notifications:
          webhooks: http://ben.ingary.net/hubot
