application: friend-tube
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: stylesheets/favicon.ico
  upload: stylesheets/favicon\.ico

- url: /static
  static_dir: staticfiles

- url: /style
  static_dir: stylesheets

- url: /terms
  mime_type : text
  static_files: staticfiles/terms
  upload: staticfiles/terms

- url: /list
  script: main.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
