application: simpleapp-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: stylesheets

- url: /list
  script: radiofaba.app

- url: /.*
  script: radiofaba.app

libraries:
- name: jinja2
  version: latest
