application: friend-tube
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: stylesheets/favicon.ico
  upload: stylesheets/favicon\.ico

- url: /style
  static_dir: stylesheets

- url: /staticfiles
  static_dir: staticfiles

- url: /list
  script: main.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
